name: "test-nix"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-nix-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix run .#poetry -- --version
      # Check everything looks valid, including shell scrips...
      - run: nix flake check
      # Actually try installing all packages at least
      - run: nix run .#poetry install
